name: frontend-prod-deploy

on:
  push:
    branches: ["main"]
    paths:
      - "apps/client/**"
      - "packages/shared/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm --filter @haeng-dong/shared build

      - name: Create environments from github secrets
        working-directory: ./apps/client
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env.prod
          echo "AMPLITUDE_KEY=${{ secrets.AMPLITUDE_KEY }}" >> .env.prod
          echo "KAKAO_JAVASCRIPT_KEY=${{ secrets.KAKAO_JAVASCRIPT_KEY }}" >> .env.prod
          echo "IMAGE_URL=${{ secrets.IMAGE_URL }}" >> .env.prod
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env.prod
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env.prod

      - name: Build for Prod environment
        run: pnpm --filter @haeng-dong/client build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload build results to S3
        run: aws s3 sync ./apps/client/dist s3://${{ secrets.S3_BUCKET_NAME }}/prod/ --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
